name: nlpiaenv

channels:
  - anaconda
  - conda-forge
  - defaults

dependencies:
  - botocore
  - cython
  - gensim
  - google-auth-oauthlib
  - h5py
  - jupyter
  - keras-applications
  - keras-preprocessing
  - keras
  - matplotlib
  - nltk
  # mkl packages usually already installed in Linux and Mac and they interfere with keras/tf
  - nomkl
  - numpy
  - opencv
  - pandas
  - pandoc
  - pip
  - plac
  - plotly
  - pyscaffold
  # this will fail on windows:
  # - python-annoy>=1.9.5,<2.0.0
  - pytest-cov
  - python-levenshtein
  - python==3.6
  - pyyaml
  - redis-py
  - regex
  - scipy
  - spacy
  - swig
  - tensorflow
  - tensorflow-hub

  - pip:
    - annoy
    - coverage
    - future
    - html2text
    - Keras-Applications
    - Keras-Preprocessing
    - pathlib
    - pillow
    - plyfile
    - python-levenshtein
    - qtconsole
    - scikit-learn
    - seaborn
    - theano
    - tqdm
    - wheel
